name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup dependencies (quick)
      run: |
        # Create libs directory
        New-Item -ItemType Directory -Force -Path "libs"
        
        # Clone and build LibGGPK3 libraries
        Write-Host "Setting up LibGGPK3 libraries..."
        git clone --depth 1 https://github.com/aianlinb/LibGGPK3.git tmp/LibGGPK3
        cd tmp/LibGGPK3
        
        # Build all three libraries
        dotnet build LibGGPK3/LibGGPK3.csproj -c Release --no-restore
        dotnet build LibBundle3/LibBundle3.csproj -c Release --no-restore
        dotnet build LibBundledGGPK3/LibBundledGGPK3.csproj -c Release --no-restore
        
        # Find and copy DLLs
        Get-ChildItem -Path . -Recurse -Name "LibGGPK3.dll" | Select-Object -First 1 | ForEach-Object { 
          Copy-Item $_ "../../libs/LibGGPK3.dll"
        }
        Get-ChildItem -Path . -Recurse -Name "LibBundle3.dll" | Select-Object -First 1 | ForEach-Object { 
          Copy-Item $_ "../../libs/LibBundle3.dll"
        }
        Get-ChildItem -Path . -Recurse -Name "LibBundledGGPK3.dll" | Select-Object -First 1 | ForEach-Object { 
          Copy-Item $_ "../../libs/LibBundledGGPK3.dll"
        }
        
        cd ../..
        Remove-Item -Recurse -Force tmp/LibGGPK3
        
        # Clone and build SystemExtensions
        Write-Host "Setting up SystemExtensions..."
        git clone --depth 1 https://github.com/aianlinb/SystemExtensions.git tmp/SystemExtensions
        cd tmp/SystemExtensions
        dotnet build -c Release --no-restore
        
        # Find and copy SystemExtensions.dll
        Get-ChildItem -Path . -Recurse -Name "SystemExtensions.dll" | Select-Object -First 1 | ForEach-Object { 
          Copy-Item $_ "../../libs/SystemExtensions.dll"
        }
        
        cd ../..
        Remove-Item -Recurse -Force tmp/SystemExtensions
        
        # Create dummy oo2core.dll for build testing
        New-Item -ItemType File -Path "libs/oo2core.dll" -Force
        
        # Verify dependencies
        Write-Host "Dependencies ready:"
        Get-ChildItem libs/ | ForEach-Object { Write-Host "  - $($_.Name)" }
      shell: pwsh
      
    - name: Restore dependencies
      run: dotnet restore src/GGPKExplorer/GGPKExplorer.csproj
      
    - name: Build application
      run: dotnet build src/GGPKExplorer/GGPKExplorer.csproj -c Release --no-restore
      
    - name: Test build output
      run: |
        Write-Host "Build completed successfully!"
        Write-Host "Output files:"
        Get-ChildItem src/GGPKExplorer/bin/Release/net8.0-windows/ | ForEach-Object { 
          Write-Host "  - $($_.Name)" 
        }
      shell: pwsh